=== SorceryDB/sorcery-cards-json/schema/card_schema.json
{
    "$id": "https://github.com/Alsciende/netrunner-cards-json/blob/master/schema/card_schema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "oneOf": [
        {
            "properties": {
                "type_code": {
                    "const": "avatar"
                }
            },
            "required": [
                "health",
                "power"
            ]
        },
        {
            "properties": {
                "type_code": {
                    "const": "agenda"
                }
            },
            "required": [
                "advancement_cost",
                "agenda_points"
            ]
        },
        {
            "properties": {
                "type_code": {
                    "enum": [
                        "asset",
                        "upgrade"
                    ]
                }
            },
            "required": [
                "cost",
                "trash_cost"
            ]
        },
        {
            "properties": {
                "type_code": {
                    "enum": [
                        "ice"
                    ]
                }
            },
            "required": [
                "cost",
                "strength"
            ]
        },
        {
            "properties": {
                "type_code": {
                    "enum": [
                        "event",
                        "hardware",
                        "operation",
                        "program",
                        "resource"
                    ]
                }
            },
            "required": [
                "cost"
            ]
        },
        {
            "properties": {
                "type_code": {
                    "const": "identity"
                }
            },
            "required": [
                "influence_limit",
                "minimum_deck_size"
            ]
        },
        {
            "properties": {
                "type_code": {
                    "enum": [
                        "site"
                    ]
                }
            },
            "required": [
                "threshold_granted_earth",
                "threshold_granted_fire",
                "threshold_granted_total",
                "threshold_granted_water",
                "threshold_granted_wind"
            ]
        }
    ],
    "properties": {
        "advancement_cost": {
            "minimum": 0,
            "type": "integer"
        },
        "agenda_points": {
            "minimum": 0,
            "type": "integer"
        },
        "base_link": {
            "minimum": 0,
            "type": "integer"
        },
        "code": {
            "pattern": "^[0-9]{5}$",
            "type": "string"
        },
        "cost": {
            "oneOf": [
                {
                    "minimum": 0,
                    "type": "integer"
                },
                {
                    "type": "null"
                }
            ]
        },
        "deck_limit": {
            "minimum": 1,
            "type": "integer"
        },
        "faction_code": {
            "minLength": 1,
            "type": "string"
        },
        "faction_cost": {
            "minimum": 0,
            "type": "integer"
        },
        "flavor": {
            "minLength": 1,
            "type": "string"
        },
        "health": {
            "minimum": 0,
            "type": "integer"
        },
        "illustrator": {
            "pattern": ".+",
            "type": "string"
        },
        "influence_limit": {
            "oneOf": [
                {
                    "minimum": 0,
                    "type": "integer"
                },
                {
                    "type": "null"
                }
            ]
        },
        "keywords": {
            "minLength": 1,
            "type": "string"
        },
        "memory_cost": {
            "minimum": 0,
            "type": "integer"
        },
        "minimum_deck_size": {
            "minimum": 0,
            "type": "integer"
        },
        "nouns": {
            "minLength": 1,
            "type": "string"
        },
        "pack_code": {
            "maxLength": 5,
            "minLength": 2,
            "type": "string"
        },
        "position": {
            "minimum": 1,
            "type": "integer"
        },
        "power": {
            "minimum": 0,
            "type": "integer"
        },
        "quantity": {
            "minimum": 1,
            "type": "integer"
        },
        "rarity_code": {
            "minLength": 0,
            "type": "string"
        },
        "strength": {
            "oneOf": [
                {
                    "type": "integer"
                },
                {
                    "type": "null"
                }
            ]
        },
        "stripped_text": {
            "minLength": 1,
            "type": "string"
        },
        "stripped_title": {
            "minLength": 1,
            "type": "string"
        },
        "stripped_type_line": {
            "minLength": 1,
            "type": "string"
        },
        "text": {
            "minLength": 1,
            "type": "string"
        },
        "threshold_granted_earth": {
            "minimum": 0,
            "type": "integer"
        },
        "threshold_granted_fire": {
            "minimum": 0,
            "type": "integer"
        },
        "threshold_granted_total": {
            "minimum": 0,
            "type": "integer"
        },
        "threshold_granted_water": {
            "minimum": 0,
            "type": "integer"
        },
        "threshold_granted_wind": {
            "minimum": 0,
            "type": "integer"
        },
        "title": {
            "minLength": 1,
            "type": "string"
        },
        "trash_cost": {
            "minimum": 0,
            "type": "integer"
        },
        "type_code": {
            "minLength": 1,
            "type": "string"
        },
        "type_line": {
            "minLength": 1,
            "type": "string"
        },
        "uniqueness": {
            "type": "boolean"
        }
    },
    "required": [
        "code",
        "deck_limit",
        "pack_code",
        "position",
        "quantity",
        "title",
        "type_code",
        "uniqueness"
    ],
    "type": "object"
}

=== SorceryDB/sorcery-cards-json/pack/pksc.json
[
    {
        "code": "02000",
        "deck_limit": 1,
        "health": 20,
        "pack_code": "pksc",
        "position": 1,
        "power": 1,
        "quantity": 1,
        "stripped_text": "Spellcaster\nTap to play a site or to draw from your atlas.\nYou start the game with 4 spells in your hand instead of 3.",
        "stripped_title": "Sorcerer",
        "stripped_type_line": "Your Avatar will win, no contest.",
        "title": "Sorcerer",
        "type_code": "avatar",
        "uniqueness": false
    }
]
