=== SorceryDB/sorcery-cards-json/schema/type_schema.json
{
    "$id": "https://github.com/Alsciende/netrunner-cards-json/blob/master/schema/type_schema.json",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "properties": {
        "code": {
            "minLength": 1,
            "type": "string"
        },
        "is_subtype": {
            "type": "boolean"
        },
        "name": {
            "minLength": 1,
            "type": "string"
        },
        "position": {
            "type": "integer"
        }
    },
    "required": [
        "code",
        "name"
    ],
    "type": "object"
}

=== SorceryDB/sorcery-cards-json/types.json
[
    {
        "code": "agenda",
        "is_subtype": false,
        "name": "Agenda",
        "position": 1
    },
    {
        "code": "avatar",
        "is_subtype": false,
        "name": "Avatar",
        "position": 1
    },
    {
        "code": "site",
        "is_subtype": false,
        "name": "Site",
        "position": 8
    },
    {
        "code": "asset",
        "is_subtype": false,
        "name": "Asset",
        "position": 2
    },
    {
        "code": "barrier",
        "is_subtype": true,
        "name": "Barrier",
        "position": 5
    },
    {
        "code": "code-gate",
        "is_subtype": true,
        "name": "Code Gate",
        "position": 6
    },
    {
        "code": "event",
        "is_subtype": false,
        "name": "Event",
        "position": 11
    },
    {
        "code": "hardware",
        "is_subtype": false,
        "name": "Hardware",
        "position": 12
    },
    {
        "code": "ice",
        "is_subtype": false,
        "name": "Ice",
        "position": 8
    },
    {
        "code": "icebreaker",
        "is_subtype": true,
        "name": "Icebreaker",
        "position": 14
    },
    {
        "code": "identity",
        "is_subtype": false,
        "name": "Identity",
        "position": 0
    },
    {
        "code": "operation",
        "is_subtype": false,
        "name": "Operation",
        "position": 4
    },
    {
        "code": "program",
        "is_subtype": false,
        "name": "Program",
        "position": 15
    },
    {
        "code": "resource",
        "is_subtype": false,
        "name": "Resource",
        "position": 13
    },
    {
        "code": "sentry",
        "is_subtype": true,
        "name": "Sentry",
        "position": 7
    },
    {
        "code": "upgrade",
        "is_subtype": false,
        "name": "Upgrade",
        "position": 3
    }
]
